server:
  port: 8080
spring:
  application:
    name: crm-kiki
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://nanakomast.mysql.zhangbei.rds.aliyuncs.com/crm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: paul
    password: 524860578lL
#  thymeleaf:
#    cache: false
#  resources:
#    static-locations: classpath:/static/, classpath:/templates/

  mvc:
    static-path-pattern: /static/**
    view:
      prefix: classpath:/templates/
      suffix: .html

mybatis:
  mapperLocations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.kiki.crm.domain
#  configuration:
logging:
  level:
    com.kiki.crm.dao : debug
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl