server:
  port: 8080
spring:
  profiles:
    active: develop
  application:
    name: crm-kiki

#  thymeleaf:
#    cache: false
#  resources:
#    static-locations: classpath:/static/, classpath:/templates/

  mvc:
    static-path-pattern: /static/**
    view:
      prefix: classpath:/templates/
      suffix: .html

mybatis:
  mapperLocations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.kiki.crm.domain
#  configuration:
logging:
  level:
    com.kiki.crm.dao : debug
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

