spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/crm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
